"""fix_retake_permission_cascade_delete

Revision ID: 441b2d4b00c3
Revises: 7c3a6c4a25de
Create Date: 2026-02-13 20:48:17.849028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441b2d4b00c3'
down_revision: Union[str, None] = '7c3a6c4a25de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('retake_permissions_test_id_fkey', 'retake_permissions', type_='foreignkey')
    op.drop_constraint('retake_permissions_teacher_id_fkey', 'retake_permissions', type_='foreignkey')
    op.drop_constraint('retake_permissions_student_id_fkey', 'retake_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'retake_permissions', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retake_permissions', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retake_permissions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retake_permissions', type_='foreignkey')
    op.drop_constraint(None, 'retake_permissions', type_='foreignkey')
    op.drop_constraint(None, 'retake_permissions', type_='foreignkey')
    op.create_foreign_key('retake_permissions_student_id_fkey', 'retake_permissions', 'users', ['student_id'], ['id'])
    op.create_foreign_key('retake_permissions_teacher_id_fkey', 'retake_permissions', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key('retake_permissions_test_id_fkey', 'retake_permissions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###

