"""fix_cascade_deletions

Revision ID: 7c3a6c4a25de
Revises: 7fcdaa1039ca
Create Date: 2026-02-13 19:33:04.774100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3a6c4a25de'
down_revision: Union[str, None] = '7fcdaa1039ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_submission_id_fkey', 'answers', type_='foreignkey')
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answers', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('retake_permissions_submission_id_fkey', 'retake_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'retake_permissions', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submissions_student_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_variant_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'test_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_questions_question_id_fkey', 'test_questions', type_='foreignkey')
    op.drop_constraint('test_questions_test_id_fkey', 'test_questions', type_='foreignkey')
    op.create_foreign_key(None, 'test_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'test_questions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_variants_test_id_fkey', 'test_variants', type_='foreignkey')
    op.create_foreign_key(None, 'test_variants', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_variants', type_='foreignkey')
    op.create_foreign_key('test_variants_test_id_fkey', 'test_variants', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.create_foreign_key('test_questions_test_id_fkey', 'test_questions', 'tests', ['test_id'], ['id'])
    op.create_foreign_key('test_questions_question_id_fkey', 'test_questions', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_variant_id_fkey', 'submissions', 'test_variants', ['variant_id'], ['id'])
    op.create_foreign_key('submissions_student_id_fkey', 'submissions', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'retake_permissions', type_='foreignkey')
    op.create_foreign_key('retake_permissions_submission_id_fkey', 'retake_permissions', 'submissions', ['submission_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_id_fkey', 'answers', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('answers_submission_id_fkey', 'answers', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###

