"""remove_question_title

Revision ID: 9f63974dc48e
Revises: 69f264f57e8f
Create Date: 2026-01-15 13:01:09.243071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f63974dc48e'
down_revision: Union[str, None] = '69f264f57e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

