"""remove teacher app work fields

Revision ID: remove_work_fields_001
Revises: 20260126_1800
Create Date: 2026-01-26 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'remove_work_fields_001'
down_revision: Union[str, None] = '20260126_1800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_applications', 'comment')
    op.drop_column('teacher_applications', 'position')
    op.drop_column('teacher_applications', 'department')
    op.drop_column('teacher_applications', 'institution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_applications', sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('teacher_applications', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('teacher_applications', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teacher_applications', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
