"""fix_retake_permission_ondelete

Revision ID: 7fcdaa1039ca
Revises: a9060c514d6b
Create Date: 2026-02-13 19:02:52.890454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcdaa1039ca'
down_revision: Union[str, None] = 'a9060c514d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('retake_permissions_submission_id_fkey', 'retake_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'retake_permissions', 'submissions', ['submission_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retake_permissions', type_='foreignkey')
    op.create_foreign_key('retake_permissions_submission_id_fkey', 'retake_permissions', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###

